server:
  port: 8080
spring:
  output:
    ansi:
      enabled: ALWAYS
  config:
    import: optional:application-secret.yml
  datasource:
    url: jdbc:mysql://localhost:3306/folio
    username: fo
    password: fo1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    com.dd.blog: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.hibernate.orm.jdbc.extract: WARN
    org.springframework.transaction.interceptor: WARN

custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:3000"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: mingleservice.site
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.blog.${custom.prod.cookieDomain}"
  site:
    name: "MINGLE DEV"
    cookie:
      secure: false
      sameSite: Lax
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
cloud:
  aws:
    region: ap-northeast-2
    s3:
      bucket: re-cord
